---
# tasks file for roles/ocp-load-kernel-modules

# Task Apply the MachineConfigPool uses the k8s module to apply the generated MachineConfig for each node type (master and worker) in the OpenShift cluster.
- name: Create MachineConfig
  k8s:
    kind: MachineConfig
    state: present
    definition: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        labels:
          machineconfiguration.openshift.io/role: {{ item }}
        name: load-kernel-modules-{{ item }}
      spec:
        config:
          ignition:
            version: 3.2.0
          storage:
            "{{kernel_module_content}}"
    validate:
      fail_on_error: yes
    loop: "{{ node_types }}"
