---
# defaults file for ocp-vlan-prun
enable_vlan_pruning_content: |
  #!/bin/bash

  ETH_INTERFACES=$(find /sys/class/net -mindepth 1 -maxdepth 1 -lname '*virtual*' -prune -o -printf '%f\n')
  echo "Enabling vlan pruning on following interfaces $ETH_INTERFACES"

  for interface in $ETH_INTERFACES
  do
      output=$(ethtool --set-priv-flags $interface vf-vlan-pruning on 2>&1)
      if [ $? -ne 0 ]; then
          echo "Vlan pruning not supported on $interface"
          echo $output
      fi
  done

kernel_unit_vlan_module_content: | 
    units:
    - contents: '[Unit]
        Description=enable vlan pruning
        After=docker.service
        After=oot-driver-load.service
        Before=kubelet.service
        [Service]
        Type=oneshot
        TimeoutStartSec=25m
        RemainAfterExit=true
        ExecStart=/usr/local/bin/enable_vlan_pruning.sh
        StandardOutput=journal+console
        [Install]
        WantedBy=default.target
        '
      enabled: true
      name: vlan-pruning.service