---
# defaults file for ocp-vlan-prun
enable_vlan_prunning_content: |
    files:
    - contents:
        source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCkVUSF9JTlRFUkZBQ0VTPSQoZmluZCAvc3lzL2NsYXNzL25ldCAtbWluZGVwdGggMSAtbWF4ZGVwdGggMSAtbG5hbWUgJyp2aXJ0dWFsKicgLXBydW5lIC1vIC1wcmludGYgJyVmXG4nKQplY2hvICJFbmFibGluZyB2bGFuIHBydW5pbmcgb24gZm9sbG93aW5nIGludGVyZmFjZXMgJEVUSF9JTlRFUkZBQ0VTIgoKZm9yIGludGVyZmFjZSBpbiAkRVRIX0lOVEVSRkFDRVMKZG8KICAgIG91dHB1dD0kKGV0aHRvb2wgLS1zZXQtcHJpdi1mbGFncyAkaW50ZXJmYWNlIHZmLXZsYW4tcHJ1bmluZyBvbiAyPiYxKQogICAgaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgICAgICAgZWNobyAiVmxhbiBwcnVuaW5nIG5vdCBzdXBwb3J0ZWQgb24gJGludGVyZmFjZSIKICAgICAgICBlY2hvICRvdXRwdXQKICAgIGZpCmRvbmUK
      mode: 493
      path: /usr/local/bin/enable_vlan_pruning.sh
kernel_unit_vlan_module_content: | 
    units:
    - contents: '[Unit]
        Description=enable vlan pruning
        After=docker.service
        After=oot-driver-load.service
        Before=kubelet.service
        [Service]
        Type=oneshot
        TimeoutStartSec=25m
        RemainAfterExit=true
        ExecStart=/usr/local/bin/enable_vlan_pruning.sh
        StandardOutput=journal+console
        [Install]
        WantedBy=default.target
        '
      enabled: true
      name: vlan-pruning.service