---
- name: "Create PerformanceProfile Resource"
  k8s:
    definition: |
      apiVersion: performance.openshift.io/v2
      kind: PerformanceProfile
      metadata:
        annotations:
          kubeletconfig.experimental: {{ kubeletconfig_annotation | to_json }}
        name: {{ item }}-profile
      spec:
        additionalKernelArgs: {{ additional_kernel_args }}
        cpu:
          isolated: {{ cpu_config[ocp_cluster][item]['isolated'] }}
          reserved: {{ cpu_config[ocp_cluster][item]['reserved'] }}
        globallyDisableIrqLoadBalancing: {{ globally_disable_irq_load_balancing }}
        hugepages:
          defaultHugepagesSize: {{ default_hugepages_size }}
          pages:
            - count: {{ pages_count[ocp_cluster] }}
              size: {{ pages_size }}
        machineConfigPoolSelector:
          pools.operator.machineconfiguration.openshift.io/{{ item }}: ''
        nodeSelector:
          node-role.kubernetes.io/{{ item }}: ''
        numa:
          topologyPolicy: {{ numa_topology_policy }}
        realTimeKernel:
          enabled: {{ real_time_kernel_enabled }}
    state: present
  loop: "{{ node_types }}"
