---
# tasks file for roles/ocp-sos

# Task install pre-requisites installs the required Python packages openshift, pyyaml, and kubernetes using the pip module.
- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
    

# Task Apply the MachineConfigPool uses the k8s module to apply the generated MachineConfig for each node type (master and worker) in the OpenShift cluster.
- name: Create MachineConfig
  k8s:
    kind: MachineConfig
    state: present
    name: "99-{{ item }}-toolboxrc-configuration"
    definition:
      metadata:
        labels:
          machineconfiguration.openshift.io/role: "{{ item }}"
      spec:
        config:
          ignition:
            version: 3.1.0
            config: {}
            security:
              tls: {}
            timeouts: {}
          networkd: {}
          passwd: {}
          storage:
            files:
            - contents:
                source: "data:text/plain;charset=utf-8;base64,{{ toolboxrc_content | b64encode }}"
              mode: 420
              overwrite: true
              path: /root/.toolboxrc
        osImageURL: ""
  loop: "{{ node_types }}"
