---
# tasks file for roles/ocp-sos

# Task install pre-requisites installs the required Python packages openshift, pyyaml, and kubernetes using the pip module.
- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
    
# Task Encode the toolboxrc_content content in base64 encodes the toolboxrc_content variable (assumed to be defined elsewhere) in base64 and stores the result in the encoded_variable fact.
- name: Encode the toolboxrc_content content in base64
  set_fact:
    toolboxrc_base64_content: "{{ toolboxrc_content | b64encode }}"

# Task Apply the MachineConfigPool uses the k8s module to apply the generated MachineConfig for each node type (master and worker) in the OpenShift cluster.
- name: Create MachineConfig
  k8s:
    kind: MachineConfig
    state: present
    name: "99-{{ item }}-toolboxrc-configuration"
    definition:
      metadata:
        labels:
          machineconfiguration.openshift.io/role: "{{ item }}"
      spec:
        config:
          ignition:
            version: 3.1.0
            config: {}
            security:
              tls: {}
            timeouts: {}
          networkd: {}
          passwd: {}
          storage:
            files:
            - contents:
                source: "{{ toolboxrc_base64_content }}"
              mode: 420
              overwrite: true
              path: /root/.toolboxrc
        osImageURL: ""
  loop: "{{ node_types }}"
