---
# defaults file for roles/ocp-mirror
registry_fqdn: "fedora.fritz.box"
registry_port: "5000"

# define the default variables for the registry dependency variables
registry_directory: /apps/registry
registry_data_dir: "{{ registry_directory }}/data"
registry_auth_dir: "{{ registry_directory }}/auth"
registry_certs_dir: "{{ registry_directory }}/certs"
registry_username: 'pi'
registry_password: 'raspberry'
imageset_directory: /apps/cluster-operators
pull_secret_directory: "/home/{{system_user_username}}/.docker"

release_profile: "DU"
release_version: "23R4"
