---
- name: Change MachineConfigPool {{ machineconfigpool_name }} state
  kubernetes.core.k8s:
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: "{{ machineconfigpool_name }}"
      spec:
        paused: "{{ machineconfigpool_paused | bool }}"
    state: present

- block:
  - name: Get MachineConfigPool status
    kubernetes.core.k8s_info:
      api_version: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      name: "{{ machineconfigpool_name }}"
    register: mcp_info

  - name: Print MachineConfigPool status
    ansible.builtin.debug:
      msg:
      - "- RENDER DEGRADED: {{ mcp_info.resources[0].status.conditions[0].status }}"
      - "- NODE DEGRADED: {{ mcp_info.resources[0].status.conditions[1].status }}"
      - "- DEGRADED: {{ mcp_info.resources[0].status.conditions[2].status }}"
      - "- UPDATED: {{ mcp_info.resources[0].status.conditions[3].status }}"
      - "- UPDATING: {{ mcp_info.resources[0].status.conditions[4].status }}"
      verbosity: 2

  - name: Wait until MachineConfigPool progressed
    kubernetes.core.k8s_info:
      api_version: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      name: "{{ machineconfigpool_name }}"
    register: mcp_status
    until:
      - mcp_status.resources | length > 0
      - mcp_status.resources[0].status.conditions[0].status == 'False'  # Render Degraded
      - mcp_status.resources[0].status.conditions[1].status == 'False'  # Node Degraded
      - mcp_status.resources[0].status.conditions[2].status == 'False'  # Degraded
      - mcp_status.resources[0].status.conditions[3].status == 'True'   # Updated
      - mcp_status.resources[0].status.conditions[4].status == 'False'  # Updating
    retries: "{{ retries_var | default(90) }}"
    delay: "{{ delay_var | default(10) }}"      # default timeout ==> retries x delay = 900sec

  - name: Print MachineConfigPool status
    ansible.builtin.debug:
      msg:
      - "- RENDER DEGRADED: {{ mcp_status.resources[0].status.conditions[0].status }}"
      - "- NODE DEGRADED: {{ mcp_status.resources[0].status.conditions[1].status }}"
      - "- DEGRADED: {{ mcp_status.resources[0].status.conditions[2].status }}"
      - "- UPDATED: {{ mcp_status.resources[0].status.conditions[3].status }}"
      - "- UPDATING: {{ mcp_status.resources[0].status.conditions[4].status }}"
      verbosity: 2
  when: machineconfigpool_paused | lower == 'false' # when unpausing