---
# defaults file for roles/ocp-sos
use_debug_tasks: true  # Change this to 'false' to skip debug tasks
toolboxrc_content: |
    REGISTRY=${OFFLINE_REG}:${OFFLINE_REG_PORT}
    IMAGE=${OFFLINE_REG}:${OFFLINE_REG_PORT}/${OFFLINE_REG_NAMESPACE}/rhel8/support-tools
    TOOLBOX_NAME=toolbox
