---
# tasks file for ocp-vlan-prun

# Task Apply the MachineConfigPool uses the k8s module to apply the generated MachineConfig for each node type (master and worker) in the OpenShift cluster.
- name: Create MachineConfig
  k8s:
    kind: MachineConfig
    state: present
    definition: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        labels:
          machineconfiguration.openshift.io/role: {{ item }}
        name: 20-enable-vlan-prunning-{{ item }}
      spec:
        config:
          ignition:
            version: 3.2.0
          storage:
            "{{enable_vlan_prunning_content}}"
          systemd:
            "{{kernel_unit_vlan_module_content}}"
    validate:
      fail_on_error: yes
    loop: "{{ node_types }}"
