23R3:
  ocp-release: "4.12.21"
  day2-operators:
    du:
      cincinnati-operator: "5.0.1"
      cluster-logging: "5.7.2"
      lvms-operator: "4.12.1"
      ptp-operator: "4.12.0-202305270029"
      sriov-network-operator: "4.12.0-202306031829"
    cu:
      elasticsearch-operator: "5.7.2"
      local-storage-operator: "4.12.0-202305262042"
      mcg-operator: "4.12.4-rhodf"
      ocs-operator: "4.12.4-rhodf"
      odf-operator: "4.12.4-rhodf"
23R4:
  ocp-release: "4.12.32"
  day2-operators:
    du:
      cincinnati-operator: "5.0.1"
      cluster-logging: "5.7.5"
      lvms-operator: "4.12.1"
      ptp-operator: "4.12.0-202308231047"
      sriov-network-operator: "4.12.0-202308231047"
    cu:
      elasticsearch-operator: "5.7.5"
      local-storage-operator: "4.12.0-202308231047"
      mcg-operator: "4.12.7-rhodf"
      ocs-operator: "4.12.7-rhodf"
      odf-operator: "4.12.7-rhodf"
