---

#- name: Display Host OS Distribution
#  debug:
#    var: ansible_facts['distribution']

# Installing the dependencies required
- name: Install required packages (Podman, httpd-tools and python3.11)
  package:
    name: "{{ item }}"
    state: present
  loop:
    - podman
    - httpd-tools
    - python3.11
    - libselinux-python3
  become: true
  when: "'RedHat' in ansible_facts['distribution']"

- name: Install required pip packages (openshift, pyyaml, kubernetes and passlib)
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
      - passlib
      - pyOpenSSL
  become: true
  when: "'RedHat' in ansible_facts['distribution']"

- name: Collect only facts returned by facter
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!<any valid subset>'
      - facter

# Check if the ocpdiscon-registry is running 
#if true skip the Offline Registry Deployment block otherwise do it
- name: Get container-ocpdiscon-registry.service Status
  ansible.builtin.systemd:
    name: "container-ocpdiscon-registry"
  register: ocpdiscon_registry_status
# Display the status of the ocpdiscon-registry check
- name: Display ocpdiscon_registry_status
  debug:
    msg: "{{ocpdiscon_registry_status.status.ActiveState}}"

- name: Offline Registry Deployment
  tags: offline-registry
  block:
  # Make sure that the directories exists otherwise those will be created
  - name: Check if directories exist
    stat:
      path: "{{ item }}"
    loop:
      - "{{ registry_data_dir }}"
      - "{{ registry_auth_dir }}"
      - "{{ registry_certs_dir }}"
      - "{{ imageset_directory }}"
    register: dir_check_results
    ignore_errors: true

  # Create the directories if not existing already
  - name: Create directory structure if needed
    file:
      path: "{{ item.item }}"
      owner: midu  # Replace with the desired owner
      group: midu  # Replace with the desired group
      state: directory
      recurse: yes
    loop: "{{ dir_check_results.results }}"
    when: not item.stat.exists
    become: true

  - name: Generate a self-signed private key
    community.crypto.openssl_privatekey:
      path: "{{registry_certs_dir}}/domain-reg.key"
      size: 4096
      mode: '0775'
      type: RSA
      format: pkcs1
      cipher: sha256
      passphrase: ""
      regenerate: "full_idempotence"
      return_content: false
      state: present
    become: true

  - name: Create certificate signing request (CSR) for self-signed certificate
    community.crypto.openssl_csr:
      path: "{{registry_certs_dir}}/domain-reg.csr"
      privatekey_path: "{{registry_certs_dir}}/domain-reg.key"
      country_name: "{{ cert_c }}"
      state_or_province_name: "{{ cert_s }}"
      locality_name: "{{ cert_l }}"
      organization_name: "{{ cert_o }}"
      organizational_unit_name: "{{ cert_ou }}"
      common_name: "{{ cert_cn }}"
      subject_alt_name: "DNS:{{ host_fqdn }}"
      subject_alt_name_critical: true
    become: true

  - name: Generate a self-signed SSL/TLS certificate (valid for 1 years)
    community.crypto.x509_certificate:
      path: "{{registry_certs_dir}}/domain-reg.crt"
      privatekey_path: "{{registry_certs_dir}}/domain-reg.key"
      csr_path: "{{registry_certs_dir}}/domain-reg.csr"
      provider: selfsigned
      selfsigned_not_after: "+365d"
      mode: '0775'
    become: true

  - name: Copy domain-reg.crt to CA trust anchors directory
    copy:
      src: "{{registry_certs_dir}}/domain-reg.crt"
      dest: /etc/pki/ca-trust/source/anchors/
      mode: '0775'
    become: true
    register: copy_result
#    notify:
#        - restart ocpdiscon-registry

  - name: Update CA trust
    command: update-ca-trust
    become: true
    when: copy_result.changed

  - name: Add a user to the Offline Registry
    community.general.htpasswd:
      path: "{{registry_auth_dir}}/htpasswd"
      name: pi
      password: 'raspberry'
      owner: root
      crypt_scheme: bcrypt
      mode: 0640
    become: true

  # Changing the file structure and files permission to the system username
  # This measure its ensuring that we are not going to rely on the root or any elevated system user
  - name: Change ownership of directories
    file:
      path: "{{ item }}"
      recurse: yes
      owner: midu  # Replace with the desired owner
      group: midu  # Replace with the desired group
    loop: 
      - "{{ registry_data_dir }}"
      - "{{ registry_auth_dir }}"
      - "{{ registry_certs_dir }}"
    become: true

  - name: Run Offline Registry Container
    containers.podman.podman_container:
      name: ocpdiscon-registry
      image: quay.io/midu/registry:latest
      ports:
        - "5000:5000"
      env:
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_REALM: Registry
        REGISTRY_HTTP_SECRET: ALongRandomSecretForRegistry
        REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain-reg.crt
        REGISTRY_HTTP_TLS_KEY: /certs/domain-reg.key
        REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED: true
        REGISTRY_STORAGE_DELETE_ENABLED: true
      volumes:
        - "{{registry_data_dir}}:/var/lib/registry:z"
        - "{{registry_auth_dir}}:/auth:z"
        - "{{registry_certs_dir}}:/certs:z"
      state: started

  # Generate rootless systemd ocpdiscon-registry.service to manage LCM
  - name: Generate systemd service unit file for ocpdiscon-registry container
    containers.podman.podman_generate_systemd:
      name: ocpdiscon-registry
      new: true
      dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/"
    register: systemd_generation_result

  #- name: Show systemd generation result
  #  debug:
  #    var: systemd_generation_result

  # Rootless systemd ocpdiscon-registry.service to manage LCM
  - name: Ensure ocpdiscon-registry container is started and enabled
    ansible.builtin.systemd:
      name: container-ocpdiscon-registry
      state: started
      enabled: true
      daemon_reload: true
      scope: user
#  handlers:
#      - name: restart ocpdiscon-registry
#        systemd:
#          name: ocpdiscon-registry
#          enabled: yes
#          state: restarted
  when: ocpdiscon_registry_status.status.ActiveState != 'active'

- name: Copy file from Ansible role to localhost
  copy:
    dest: "{{imageset_directory}}/release_versions.yml"
    content: |
      ---
      23R3:
        ocp-release: "4.12.21"
        day2-operators:
          du:
            cincinnati-operator: "5.0.1"
            cluster-logging: "5.7.2"
            lvms-operator: "4.12.1"
            ptp-operator: "4.12.0-202305270029"
            sriov-network-operator: "4.12.0-202306031829"
          cu:
            elasticsearch-operator: "5.7.2"
            local-storage-operator: "4.12.0-202305262042"
            mcg-operator: "4.12.4-rhodf"
            ocs-operator: "4.12.4-rhodf"
            odf-operator: "4.12.4-rhodf"
      23R4:
        ocp-release: "4.12.29"
        day2-operators:
          du:
            cincinnati-operator: "5.0.1"
            cluster-logging: "5.7.4"
            lvms-operator: "4.12.1"
            ptp-operator: "4.12.0-202307262354"
            sriov-network-operator: "4.12.0-202307270623"
          cu:
            elasticsearch-operator: "5.7.4"
            local-storage-operator: "4.12.0-202307182142"
            mcg-operator: "4.12.5-rhodf"
            ocs-operator: "4.12.5-rhodf"
            odf-operator: "4.12.5-rhodf"
    setype: user_home_t
    seuser: unconfined_u
    selevel: s0
    mode: '0664'

- name: Template the imageset-config.yaml file
  containers.podman.podman_container:
    name: imageset-config-templater
    image: quay.io/midu/imageset-config-release-templater:latest
    env:
      RELEASE_VERSION: "23R3"
      RELEASE_PROFILE: "CU"
    volumes:
      - "{{imageset_directory}}:/cluster-operators:z"
    state: started